### ISSUE TITLE
Recording wrong application

### ISSUE THREAD

**Issue by Asgaroth** [lulzsun/RePlays#122]
I am trying to record League of Legends and I have Chrome with a video playing. When the game starts RePlays correctly starts recording, after finishing tho, the recording is of the video in chrome and not the game

![image](https://github.com/lulzsun/RePlays/assets/755568/28d133fe-e54b-4825-bae5-fb41ebb31553)

![image](https://github.com/lulzsun/RePlays/assets/755568/88c53bc1-ffa8-4431-bd7c-59f9b3978bd2)

**Comment by lulzsun** [comment]
Are you on stable release? Nightly had some changes made with regards to the recording backend that may solve this issue.

The reason why this happens is because the game capture mode failed. When that happens we default to display capture mode, which is probably why you see recording of chrome and your taskbar.

Is this recording a second display? If so, is this display defined as your primary monitor?

**Comment by Asgaroth** [comment]
Thanks for the quick reply.

Yes, I just installed the app yesterday from the last stable release.
I only have one monitor.
My league client seems bugged in that I have it on windowed borderless but it keeps resetting to fullscreen, not sure if that is causing the game capture mode to break. Will test nightly later today.

**Comment by Asgaroth** [comment]
It seems to be working now. No wrong recordings last night. Thank you!

And thank you for reviving this!

**Comment by Asgaroth** [comment]
I see a new behavior, it will now record both the browser and the game, but it will only record the game for 30 seconds before stoping. The first few minutes are the browser.

![image](https://github.com/lulzsun/RePlays/assets/755568/03bc6f1f-1421-4386-8589-ad2b439be013)

**Comment by lulzsun** [comment]
Interesting behavior, does it appear to happen often? I am currently investigating such recording issues and would like any details if you can find any correlation to this occurrence. It does not appear to occur on my machine so I am unable to understand the reason behind this issue.

Also feel free to provide the logs here, they might help in solving the issue. They can be retrieved through Settings > Help.

**Comment by Asgaroth** [comment]
Thank you for looking into it. Originally I had a hint it had to do with automanaged disk space. But it did record some games, i'd say about 3/4 games would be 1-2 min recordings, and then one full recording. I changed my settings to keep them by days instead of by disk space and will report back when I have tested tonight.

[logs.txt](https://github.com/lulzsun/RePlays/files/11818576/logs.txt)

**Comment by lulzsun** [comment]
I've pushed some _potential_ fixes towards this issue, but I am unsure if it will actually solve this particular situation. This issue has been troublesome lately because I have been unable to replicate this and other issues related to recording stopping early #124 (the dreaded, "but it works on my machine!...").

**Comment by lulzsun** [comment]
The refactoring of the recording backend has been deemed complete. A lot of related issues have been reported to be resolved but this one has gone stale for some time.

I will be closing this assuming that the issue has been resolved, but please feel free to report back if you say otherwise and I can reopen this issue. Thanks!
