### ISSUE TITLE
Streamable uploads failing

### ISSUE THREAD

**Issue by yoshinoa** [lulzsun/RePlays#126]
When I attempt to upload a clip to Streamable, I get an error: 

Failed to upload clip: System.Net.Http.HttpRequestException: Error while copying content to a stream.

Full logs here:

https://pastebin.com/eW0ZqNvA

**Comment by lulzsun** [comment]
Hi, does the file size of the clip exceed Streamable's file size limit? Free usage is under <250MB for uploading videos. Might also be an issue of invalid credentials.

**Comment by Segergren** [comment]
I just tried it out and seems to work fine too me.

**Comment by Segergren** [comment]
Should you close this @lulzsun?

**Comment by lulzsun** [comment]
I will be closing this issue since we do not have enough information available to understand the issue. Most likely it is either being over the file size limit or invalid credentials. I will be making a note of this for the future to display a more friendly error message if either of mentioned causes of upload failure occur.

Feel free to add more information and maybe we can reopen this issue to look into further.
