### ISSUE TITLE
Video not saving after auto-record

### ISSUE THREAD

**Issue by Paulchief** [lulzsun/RePlays#156]
After recording fullscreen videogames I get a preview in the sessions tab, but if I click it it's just a black screen with 00:00/00:00 length, and if I try to open it in the folder it doesn't exist. Then after restarting the app the preview also disappears

**Comment by Segergren** [comment]
Can you provide the logs @Paulchief? :)

**Comment by Paulchief** [comment]
All my settings + log file [logs.txt](https://github.com/lulzsun/RePlays/files/13253047/logs.txt)
![3](https://github.com/lulzsun/RePlays/assets/93049933/7e55d431-d3fc-474b-8874-18f06236113e)
![2](https://github.com/lulzsun/RePlays/assets/93049933/eb50094d-baee-4dc2-b7a4-375a83ef4bb9)
![1](https://github.com/lulzsun/RePlays/assets/93049933/3ab976ff-cbe3-4c67-b72c-30703aea4442)

**Comment by Segergren** [comment]
We have updated the program a lot since version 1.2.1. Can you try with the latest "Nightly" version? You can select it here:
![image](https://github.com/lulzsun/RePlays/assets/58270063/cb30ad8e-0443-48af-85b1-de045d90aa5b)
You will then have to:
1) Fully exit the application
2) Open it up
3) Wait for it to be downloaded
4) Exit the application again
5) Open it again 😁

**Comment by Paulchief** [comment]
Updating to 1.2.46 Nightly seemed to have solved the issue, thanks!
