### ISSUE TITLE
RePlays not recoding in 1.3.0

### ISSUE THREAD

**Issue by kmanc** [lulzsun/RePlays#186]
Since the update to 1.3.0 I haven't been able to record any of my games. I've tried manually adding the executable via "Detection" but that doesn't seem to do the trick either.

Not sure how to assist with troubleshooting, but if you need anything I can certainly try to help!

**Comment by Segergren** [comment]
Hi, this was fixed in 1.3.2 (https://github.com/lulzsun/RePlays/commit/38fa6a1658ff1b97066cc9e60bd79c22b484ec94) in the Nightly build. You could wait for @lulzsun to update the Stable branch or change to Nightly now and click "Check for Updates".

I believe @lulzsun also added a check to prevent this from happening in the future (https://github.com/lulzsun/RePlays/commit/38fa6a1658ff1b97066cc9e60bd79c22b484ec94#diff-7610341909818beeb2df9f616f90f47dd94921d6ec54f9c7d53846ed033e0b5cR45-R48)

**Comment by lulzsun** [comment]
Stable 1.3.0 shouldn't have an issue with missing obs.dll. Could you provide logs before trying to update to nightly?

**Comment by kmanc** [comment]
[logs.txt](https://github.com/lulzsun/RePlays/files/14828139/logs.txt)

**Comment by Segergren** [comment]
How much space do you have left on your disk @kmanc?

**Comment by lulzsun** [comment]
Looking briefly at the logs I found this error:

```
[3/31/2024 8:43:32 PM][LibObsRecorder.cs::StartRecording(434)]: LibObs output recording error: 'Unable to write to C:/Users/user/Videos/Plays/League of Legends/2024_03_31_20_43_11-ses.mp4. Make sure you're using a recording path which your user account is allowed to write to and that there is sufficient disk space.

If Windows 10 Ransomware Protection is enabled it can also cause this error. Try turning off controlled folder access in Windows Security / Virus & threat protection settings.'
```

Looks like game detection is working, but it is unable to record to a file. Does the user folder "C:/Users/user" exist? If not, then it might be grabbing an incorrect user? Or potentially there is a file permissions issue that you need to figure out.

**Comment by kmanc** [comment]
Plenty, but on a hunch I checked my Defender logs and I think I see the issue. When I updated, my controlled folder access got it

![image](https://github.com/lulzsun/RePlays/assets/14863147/c8d0ec83-f8e0-4f3a-a5cd-a5f81f6b94e7)
