### ISSUE TITLE
Instant replay / Replay buffer capturing

### ISSUE THREAD

**Issue by N72826** [lulzsun/RePlays#47]
Hey I really appreciate you for creating this. MedalTV is functional but I have a feeling their premium is going to drive it into the ground. They already made it so you can't download your uploaded clips without a watermark without paying. They also "temporarily" disabled embedding on discord, which is ridiculous.

Are there any plans to implement a clip feature that allows you to capture the last x seconds?

I see you are using OBS to perform the capturing, and what I am asking for may be extremely difficult because of this. I believe that the way this feature works is through recording all the time and deleting the recorded content that wasn't marked for capture with the chosen hotkey. I am unsure how this would be accomplished but it would truly make this platform a superior alternative to Medal.

**Comment by sonicv6** [comment]
This should be possible, I've got a few other things I'd rather do before working on this but someone else might take it up.

**Comment by N72826** [comment]
> This should be possible, I've got a few other things I'd rather do before working on this but someone else might take it up.

oh nice! I will definitely be watching this project closely. Thank you and anyone else who worked on this!

**Comment by sonicv6** [comment]
Leave the issue open so we remember it haha

**Comment by N72826** [comment]
> Leave the issue open so we remember it haha

oh shit my bad lol

**Comment by lulzsun** [comment]
OBS does have a replay buffer feature already built in, so yes, this implementation isn't too difficult. It's actually common in these types of applications. 

This will probably be implemented eventually, but as sonicv6 said, it may be awhile until it does because of other priorities. But I'll try to keep it in mind.

**Comment by candroid-man** [comment]
I downloaded this app because that's what I thought this would do 😆

**Comment by eiqnepm** [comment]
This is a really nice app! No account registration and a simple yet effective interface. The app doesn't use too much resources in the background either, I'm looking at you memory hog Medal.

I've just been playing around with it. If all you wanted to do was record whole game sessions, it's great!

Unfortunately for me, I would require push to talk and a reply buffer to use it as my primary recording software. Alas I'm stuck with Medal for now.

I'll watch for any updates on this though.

**Comment by Segergren** [comment]
@lulzsun Have you looked into it? If so, are there any part that is extra hard to implement? 
I tried to look into it about a month ago but my limited DLL/C++ skills were not enough.

**Comment by lulzsun** [comment]
It is in progress and I have got it working in an example here: [libobs.NET](https://github.com/lulzsun/libobs.NET)

However, I have not decided to implement it yet because I currently want to focus on refactoring, specially the recording back-end and the keybinding system (doing this right now as we speak). Once I feel satisfied with the refactoring, I will be ready to implement instant replay.

**Comment by Nama** [comment]
I really thought that this would be the main reason this app exists and was confused about the lack of options for this XD

**Comment by josc19** [comment]
Currently looking for a shadow play alternative that just works, shadowplay recently started to just randomly fail to load and I have no insight on what happened. I usually document bugs and crashes i run into a game im testing. OBS replay buffer is just silly since it doesn't clear the buffer on save. Medal is just gross im not touching that.

I really hope this feature becomes a thing soon.

**Comment by lulzsun** [comment]
This feature is up next on my personal TO-DO list, it's just that recently I have been busy with things unrelated this project. I'm unable to give a time frame on when I can get around implementing this, but I promise that this is the number one priority feature once I am able to find some time.

There has already been work and tests on buffer capturing using the libobs.NET library that I work on alongside this project, so all it needs is a proper implementation.

**Comment by Bmilner88** [comment]
Don't know if this is the right place to ask this, but when/if this gets implemented, will the files be Sessions? Or Clips?

I ask because I'm curious if the files will be editable after they are captured

**Comment by sonicv6** [comment]
Under the hood there's no major difference but it makes more sense for us to make them sessions precisely so you can edit them.

**Comment by sshcrack** [comment]
@lulzsun is the refactoring done? If so, would you be open to receive a pull request for this feature? Haven't looked at the libobs bindings yet but I think the methods are already implemented correct?

**Comment by lulzsun** [comment]
Yes, I did finish most of the refactoring, just haven't had the time to do a proper implementation of this feature. Feel free to draft a pull request for this and I may be able to assist if needed.

I did test and implemented the methods required for buffer capturing, there is an example of this provided here if you want to use as a reference:

https://github.com/lulzsun/libobs-sharp/blob/d4e990a5fb1c2df4383191e7eefa827d438d5a2a/libobs-sharp.example/Program.cs#L116-L127

**Comment by sshcrack** [comment]
The PR has been merged, can we close this issue?

**Comment by lulzsun** [comment]
Forgot to close this, closing now.
