### ISSUE TITLE
Audio settings volume levels not working

### ISSUE THREAD

**Issue by ThatBurgundy** [lulzsun/RePlays#62]
Audio is still recorded from both microphone and system sounds no matter what the audio settings volume sliders are set to. Below example shows the audio is recorded despite those settings being selected:
![image](https://user-images.githubusercontent.com/25126483/197012090-17f9417e-be6a-4b25-bff1-acc3b5a64a8c.png)
![image](https://user-images.githubusercontent.com/25126483/197012319-778ceb5b-8fbd-44f8-b2ba-4bd59455f2fa.png)

Using nightly RePlays build v1.0.49

My audio setup is perhaps uncommon in that I output through Sonarworks SoundID Reference into a Universal Audio Apollo Solo USB audio interface, so this might be affecting something? Please let me know if you need any other information, it would be brilliant to have just game audio (no mic, no system sound) if it were possible, but muting the audio would be the next best thing.

**Comment by lulzsun** [comment]
Sorry about this issue, it is probably because the UI controls are not yet wired to properly set the volume yet. It was working until 1.0.1+, but never got around fixing it. I'll try to look into it sometime towards this weekend.

System sounds will still be captured for some time, but we do have a plan to filter those out in the future.

**Comment by lulzsun** [comment]
Should take effect in the next nightly build. Thanks for reporting this issue!
