### ISSUE TITLE
can there be an option to select igpu over dgpu?

### ISSUE THREAD

**Issue by xdXot1c** [lulzsun/RePlays#98]
i have a laptop and would like to use the ipgu over my dedicated nvidia gpu, is there any way to do that?

**Comment by lulzsun** [comment]
The only setting that you could change to use your integrated GPU is for the encoding. You can change it in capture settings under Encoder. If you have an intel gpu, the encoder option should be "Hardware (QSV)", meaning it will be using intel QuickSync encoder.

However, I wouldn't recommend doing this because you would not get any performance benefits.

The underlying technology for recording is libobs, meaning that we essentially use a headless version of OBS Studio. Here are some OBS forum references to using an integrated or second GPU:
- [Can you use a 2nd GPU to eliminate encoder overload?](https://obsproject.com/forum/threads/can-you-use-a-2nd-gpu-to-eliminate-encoder-overload.149644)
- [How to run OBS on BOTH GPUs (Integrated + nVIDIA)](https://obsproject.com/forum/threads/how-to-run-obs-on-both-gpus-integrated-nvidia.107699/)

**Comment by lulzsun** [comment]
I will be closing this issue given the explanation above. If you think there is a reason to keep this issue open, feel free to explain.
